name: server_dart
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  postgres: ^2.6.2
  get_it: ^7.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0